from sqlalchemy.orm import Session
from app.models.merchant import Merchant
from app.schemas.merchant_schema import MerchantInput


class MerchantService:
    """
    Service layer for merchant data operations.
    
    Handles persistence of merchant information to the database.
    """
    
    @staticmethod
    def create_merchant(db: Session, merchant_input: MerchantInput) -> Merchant:
        """
        Upsert a merchant record.  If the merchant_id already exists, the
        existing row is returned unchanged (preserving mobile_number, secure_token
        etc.).  Only a genuinely new merchant triggers an INSERT.
        """
        # Check if merchant already exists — return early if so
        existing = db.query(Merchant).filter(
            Merchant.merchant_id == merchant_input.merchant_id
        ).first()
        if existing:
            return existing

        db_merchant = Merchant(
            merchant_id=merchant_input.merchant_id,
            monthly_revenue=merchant_input.monthly_revenue,
            credit_score=merchant_input.credit_score,
            years_in_business=merchant_input.years_in_business,
            existing_loans=merchant_input.existing_loans,
            past_defaults=merchant_input.past_defaults,
            # Behavioral fields
            category=getattr(merchant_input, 'category', None),
            monthly_gmv_12m=getattr(merchant_input, 'monthly_gmv_12m', []),
            coupon_redemption_rate=getattr(merchant_input, 'coupon_redemption_rate', 0.0),
            unique_customer_count=getattr(merchant_input, 'unique_customer_count', 0),
            customer_return_rate=getattr(merchant_input, 'customer_return_rate', 0.0),
            avg_order_value=getattr(merchant_input, 'avg_order_value', 0.0),
            seasonality_index=getattr(merchant_input, 'seasonality_index', 1.0),
            deal_exclusivity_rate=getattr(merchant_input, 'deal_exclusivity_rate', 0.0),
            return_and_refund_rate=getattr(merchant_input, 'return_and_refund_rate', 0.0),
            chargeback_rate=getattr(merchant_input, 'chargeback_rate', 0.0),
            # secure_token is auto-generated by SQLAlchemy default
        )
        db.add(db_merchant)
        db.commit()
        db.refresh(db_merchant)
        return db_merchant
    
    @staticmethod
    def get_by_merchant_id(db: Session, merchant_id: str) -> Merchant:
        """
        Retrieve a merchant by merchant_id.
        
        Args:
            db: SQLAlchemy database session
            merchant_id: Unique merchant identifier
            
        Returns:
            Merchant: Merchant record if found, None otherwise
        """
        return db.query(Merchant).filter(Merchant.merchant_id == merchant_id).first()
    
    @staticmethod
    def get_by_secure_token(db: Session, secure_token: str) -> Merchant:
        """
        Retrieve a merchant by secure_token (for public offer page).
        
        Args:
            db: SQLAlchemy database session
            secure_token: UUID token generated for merchant
            
        Returns:
            Merchant: Merchant record if found, None otherwise
        """
        return db.query(Merchant).filter(Merchant.secure_token == secure_token).first()
