from enum import Enum
from pydantic import BaseModel, Field


class RiskTier(str, Enum):
    """Risk tier classification for underwriting decisions."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"


class UnderwritingDecision(str, Enum):
    """Final underwriting decision outcomes."""
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PENDING_REVIEW = "PENDING_REVIEW"


class UnderwritingDecision(BaseModel):
    """
    Pydantic model for underwriting result and final decision.
    
    Encapsulates the risk assessment outcome and AI-generated decision rationale.
    Explanation is generated by Claude AI for transparency and risk analysis.
    """
    merchant_id: str = Field(..., description="Unique identifier for the merchant")
    risk_score: int = Field(..., ge=0, le=100, description="Risk score on a scale of 0-100")
    risk_tier: str = Field(..., description="Risk tier classification (Tier 1, Tier 2, Tier 3)")
    decision: str = Field(..., description="Final underwriting decision (APPROVED, APPROVED_WITH_CONDITIONS, REJECTED)")
    explanation: str = Field(..., description="AI-generated or fallback explanation for the underwriting decision")

    class Config:
        json_schema_extra = {
            "example": {
                "merchant_id": "MERCH_12345",
                "risk_score": 83,
                "risk_tier": "Tier 1",
                "decision": "APPROVED",
                "explanation": "The merchant demonstrates strong financial stability with a credit score of 780 and consistent monthly revenue of 90,000. With 6 years in operation and no history of defaults, the risk profile is classified as Tier 1. The high computed risk score of 83 supports approval."
            }
        }
