from enum import Enum
from pydantic import BaseModel, Field
from typing import Optional, List


class RiskTier(str, Enum):
    """Risk tier classification for underwriting decisions."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"


class UnderwritingDecision(str, Enum):
    """Final underwriting decisions."""
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    PENDING_REVIEW = "PENDING_REVIEW"


class CreditOffer(BaseModel):
    """
    GrabCredit financial offer for merchant.
    
    Deterministically calculated based on risk tier and merchant financials.
    """
    credit_limit_lakhs: float = Field(
        ..., 
        ge=0, 
        description="Credit limit in lakhs (1 lakh = 100,000 currency units)"
    )
    interest_rate_percent: float = Field(
        ..., 
        ge=0, 
        le=50, 
        description="Annual interest rate percentage"
    )
    tenure_options_months: List[int] = Field(
        ..., 
        description="Available loan tenure options in months"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "credit_limit_lakhs": 5.0,
                "interest_rate_percent": 12.5,
                "tenure_options_months": [6, 12, 24, 36]
            }
        }


class InsuranceOffer(BaseModel):
    """
    GrabInsurance financial offer for merchant.
    
    Deterministically calculated based on risk tier and merchant GMV.
    """
    coverage_amount_lakhs: float = Field(
        ..., 
        ge=0, 
        description="Coverage amount in lakhs"
    )
    premium_amount: float = Field(
        ..., 
        ge=0, 
        description="Annual premium amount in currency units"
    )
    policy_type: str = Field(
        ..., 
        description="Type of insurance policy (e.g., 'Basic', 'Standard', 'Premium')"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "coverage_amount_lakhs": 10.0,
                "premium_amount": 2500,
                "policy_type": "Standard"
            }
        }


class FinancialOffer(BaseModel):
    """
    Flexible financial offer union - either Credit or Insurance based on mode.
    """
    credit: Optional[CreditOffer] = Field(default=None, description="GrabCredit offer (if mode='credit')")
    insurance: Optional[InsuranceOffer] = Field(default=None, description="GrabInsurance offer (if mode='insurance')")


class UnderwritingResult(BaseModel):
    """
    Pydantic model for underwriting result and final decision.
    
    Encapsulates the risk assessment outcome and AI-generated decision rationale.
    Includes optional financial offers for Credit and Insurance modes.
    Explanation is generated by Claude AI for transparency and risk analysis.
    """
    merchant_id: str = Field(..., description="Unique identifier for the merchant")
    risk_score: int = Field(..., ge=0, le=100, description="Risk score on a scale of 0-100")
    risk_tier: str = Field(..., description="Risk tier classification (Tier 1, Tier 2, Tier 3)")
    decision: str = Field(..., description="Final underwriting decision (APPROVED, APPROVED_WITH_CONDITIONS, REJECTED)")
    explanation: str = Field(..., description="AI-generated or fallback explanation for the underwriting decision")
    financial_offer: Optional[FinancialOffer] = Field(
        default=None, 
        description="Financial offer structure containing credit and/or insurance details"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "merchant_id": "MERCH_12345",
                "risk_score": 83,
                "risk_tier": "Tier 1",
                "decision": "APPROVED",
                "explanation": "The merchant demonstrates strong financial stability with a credit score of 780 and consistent monthly revenue of 90,000. With 6 years in operation and no history of defaults, the risk profile is classified as Tier 1. The high computed risk score of 83 supports approval.",
                "financial_offer": {
                    "credit": {
                        "credit_limit_lakhs": 5.0,
                        "interest_rate_percent": 12.5,
                        "tenure_options_months": [6, 12, 24, 36]
                    },
                    "insurance": None
                }
            }
        }

# Backward compatibility alias
UnderwritingDecision = UnderwritingResult
